nyc_trends = [{'as_of': '2022-03-29T21:12:02Z',
  'created_at': '2022-03-28T10:40:19Z',
  'locations': [{'name': 'New York', 'woeid': 2459115}],
  'trends': [{'name': 'Marwin',
              'promoted_content': None,
              'query': 'Marwin',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=Marwin'},
             {'name': '#FairPay4HomeCare',
              'promoted_content': None,
              'query': '%23FairPay4HomeCare',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%23FairPay4HomeCare'},
             {'name': 'Nintendo',
              'promoted_content': None,
              'query': 'Nintendo',
              'tweet_volume': 147015,
              'url': 'http://twitter.com/search?q=Nintendo'},
             {'name': 'Pfizer',
              'promoted_content': None,
              'query': 'Pfizer',
              'tweet_volume': 107818,
              'url': 'http://twitter.com/search?q=Pfizer'},
             {'name': 'PlayStation',
              'promoted_content': None,
              'query': 'PlayStation',
              'tweet_volume': 167336,
              'url': 'http://twitter.com/search?q=PlayStation'},
             {'name': 'Julia Fox',
              'promoted_content': None,
              'query': '%22Julia+Fox%22',
              'tweet_volume': 13020,
              'url': 'http://twitter.com/search?q=%22Julia+Fox%22'},
             {'name': 'Alec Baldwin',
              'promoted_content': None,
              'query': '%22Alec+Baldwin%22',
              'tweet_volume': 34505,
              'url': 'http://twitter.com/search?q=%22Alec+Baldwin%22'},
             {'name': 'Merrick Garland',
              'promoted_content': None,
              'query': '%22Merrick+Garland%22',
              'tweet_volume': 98836,
              'url': 'http://twitter.com/search?q=%22Merrick+Garland%22'},
             {'name': 'Apple TV',
              'promoted_content': None,
              'query': '%22Apple+TV%22',
              'tweet_volume': 11489,
              'url': 'http://twitter.com/search?q=%22Apple+TV%22'},
             {'name': "Don't Say Gay",
              'promoted_content': None,
              'query': '%22Don%27t+Say+Gay%22',
              'tweet_volume': 54336,
              'url': 'http://twitter.com/search?q=%22Don%27t+Say+Gay%22'},
             {'name': 'Senegal',
              'promoted_content': None,
              'query': 'Senegal',
              'tweet_volume': 186800,
              'url': 'http://twitter.com/search?q=Senegal'},
             {'name': 'Ghana',
              'promoted_content': None,
              'query': 'Ghana',
              'tweet_volume': 277627,
              'url': 'http://twitter.com/search?q=Ghana'},
             {'name': 'Jim Carrey',
              'promoted_content': None,
              'query': '%22Jim+Carrey%22',
              'tweet_volume': 14785,
              'url': 'http://twitter.com/search?q=%22Jim+Carrey%22'},
             {'name': 'Portugal',
              'promoted_content': None,
              'query': 'Portugal',
              'tweet_volume': 161214,
              'url': 'http://twitter.com/search?q=Portugal'},
             {'name': '#SENEGY',
              'promoted_content': None,
              'query': '%23SENEGY',
              'tweet_volume': 28028,
              'url': 'http://twitter.com/search?q=%23SENEGY'},
             {'name': '#YIAYquote',
              'promoted_content': None,
              'query': '%23YIAYquote',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%23YIAYquote'},
             {'name': 'Gaetz',
              'promoted_content': None,
              'query': 'Gaetz',
              'tweet_volume': 34905,
              'url': 'http://twitter.com/search?q=Gaetz'},
             {'name': 'BOYFRIEND REVEAL',
              'promoted_content': None,
              'query': '%22BOYFRIEND+REVEAL%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22BOYFRIEND+REVEAL%22'},
             {'name': 'Cawthorn',
              'promoted_content': None,
              'query': 'Cawthorn',
              'tweet_volume': 59705,
              'url': 'http://twitter.com/search?q=Cawthorn'},
             {'name': 'Ron Perlman',
              'promoted_content': None,
              'query': '%22Ron+Perlman%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Ron+Perlman%22'},
             {'name': '#mnwildfirst',
              'promoted_content': None,
              'query': '%23mnwildfirst',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%23mnwildfirst'},
             {'name': 'Kelly Green',
              'promoted_content': None,
              'query': '%22Kelly+Green%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Kelly+Green%22'},
             {'name': '#pssssdstory',
              'promoted_content': None,
              'query': '%23pssssdstory',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%23pssssdstory'},
             {'name': 'Emmett Till',
              'promoted_content': None,
              'query': '%22Emmett+Till%22',
              'tweet_volume': 22614,
              'url': 'http://twitter.com/search?q=%22Emmett+Till%22'},
             {'name': 'Mendy',
              'promoted_content': None,
              'query': 'Mendy',
              'tweet_volume': 32966,
              'url': 'http://twitter.com/search?q=Mendy'},
             {'name': 'Nadler',
              'promoted_content': None,
              'query': 'Nadler',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=Nadler'},
             {'name': 'Mo Salah',
              'promoted_content': None,
              'query': '%22Mo+Salah%22',
              'tweet_volume': 13416,
              'url': 'http://twitter.com/search?q=%22Mo+Salah%22'},
             {'name': 'Mane',
              'promoted_content': None,
              'query': 'Mane',
              'tweet_volume': 88310,
              'url': 'http://twitter.com/search?q=Mane'},
             {'name': 'Bruno Fernandes',
              'promoted_content': None,
              'query': '%22Bruno+Fernandes%22',
              'tweet_volume': 30042,
              'url': 'http://twitter.com/search?q=%22Bruno+Fernandes%22'},
             {'name': 'Cheesecake',
              'promoted_content': None,
              'query': 'Cheesecake',
              'tweet_volume': 13646,
              'url': 'http://twitter.com/search?q=Cheesecake'},
             {'name': 'Viktor',
              'promoted_content': None,
              'query': 'Viktor',
              'tweet_volume': 26127,
              'url': 'http://twitter.com/search?q=Viktor'},
             {'name': 'Brick Ross',
              'promoted_content': None,
              'query': '%22Brick+Ross%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Brick+Ross%22'},
             {'name': 'McCarthy',
              'promoted_content': None,
              'query': 'McCarthy',
              'tweet_volume': 25180,
              'url': 'http://twitter.com/search?q=McCarthy'},
             {'name': 'Top Gun',
              'promoted_content': None,
              'query': '%22Top+Gun%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Top+Gun%22'},
             {'name': 'Zelda',
              'promoted_content': None,
              'query': 'Zelda',
              'tweet_volume': 100369,
              'url': 'http://twitter.com/search?q=Zelda'},
             {'name': 'AFCON',
              'promoted_content': None,
              'query': 'AFCON',
              'tweet_volume': 11487,
              'url': 'http://twitter.com/search?q=AFCON'},
             {'name': 'Jokic',
              'promoted_content': None,
              'query': 'Jokic',
              'tweet_volume': 17004,
              'url': 'http://twitter.com/search?q=Jokic'},
             {'name': 'Roger Goodell',
              'promoted_content': None,
              'query': '%22Roger+Goodell%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Roger+Goodell%22'},
             {'name': 'Lewandowski',
              'promoted_content': None,
              'query': 'Lewandowski',
              'tweet_volume': 19306,
              'url': 'http://twitter.com/search?q=Lewandowski'},
             {'name': 'Irsay',
              'promoted_content': None,
              'query': 'Irsay',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=Irsay'},
             {'name': 'BOTW',
              'promoted_content': None,
              'query': 'BOTW',
              'tweet_volume': 20680,
              'url': 'http://twitter.com/search?q=BOTW'},
             {'name': 'Oneil Cruz',
              'promoted_content': None,
              'query': '%22Oneil+Cruz%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Oneil+Cruz%22'},
             {'name': 'Bolton',
              'promoted_content': None,
              'query': 'Bolton',
              'tweet_volume': 13354,
              'url': 'http://twitter.com/search?q=Bolton'},
             {'name': 'Mick Mulvaney',
              'promoted_content': None,
              'query': '%22Mick+Mulvaney%22',
              'tweet_volume': 25896,
              'url': 'http://twitter.com/search?q=%22Mick+Mulvaney%22'},
             {'name': 'Start Kareem',
              'promoted_content': None,
              'query': '%22Start+Kareem%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Start+Kareem%22'},
             {'name': 'Bnei Brak',
              'promoted_content': None,
              'query': '%22Bnei+Brak%22',
              'tweet_volume': 11287,
              'url': 'http://twitter.com/search?q=%22Bnei+Brak%22'},
             {'name': 'DeSantis',
              'promoted_content': None,
              'query': 'DeSantis',
              'tweet_volume': 108548,
              'url': 'http://twitter.com/search?q=DeSantis'},
             {'name': 'Paul Rudd',
              'promoted_content': None,
              'query': '%22Paul+Rudd%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Paul+Rudd%22'},
             {'name': 'Taco Tuesday',
              'promoted_content': None,
              'query': '%22Taco+Tuesday%22',
              'tweet_volume': None,
              'url': 'http://twitter.com/search?q=%22Taco+Tuesday%22'},
             {'name': 'Macedonia',
              'promoted_content': None,
              'query': 'Macedonia',
              'tweet_volume': 62942,
              'url': 'http://twitter.com/search?q=Macedonia'}]}]



from wordcloud import WordCloud
import matplotlib.pyplot as plt

new_dict = {}

for trend in nyc_trends[0]['trends']:
    if trend['tweet_volume']:
        new_dict[trend['name']] = trend['tweet_volume']

wordcloud = WordCloud(colormap="prism", background_color="white").generate_from_frequencies(new_dict)

plt.imshow(wordcloud)
wordcloud.to_file("trends.png")
plt.show()
print("done")





